# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test:
    docker:
    - image: circleci/node:14.15.4

    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: npm install
      - run:
          name: Running some tests
          command: npm test

workflows:
  build-and-test:
    jobs:
      - test